# UNE Docker Drupal 8

version: '3.1'

services:

  drupal:
    # https://github.com/guylyons/drupal-dockerfile
    image: guylyons/drupal8:latest
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    ports:
      - 8000:80 
    volumes:
      - ./code:/var/www/drupal
      - ./sites/default:/var/www/drupal/web/sites/default   # override settings stuff
      - ./drush:/var/www/drupal/drush/sites                 # drush aliases from Pantheon
    restart: always

  mysql:
    image: mariadb:latest
    restart: always
    hostname: mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 'une'
    volumes:
      - ./db_data:/var/lib/mysql
