# UNE Docker Drupal 8

version: '3.1'

services:

  drupal:
    # https://github.com/guylyons/drupal-dockerfile
    image: guylyons/drupal:latest
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      COMPOSER_MEMORY_LIMIT: -1
      COMPOSER_PROCESS_TIMEOUT: 2000 #seconds
    ports:
      - 8000:80 
    volumes:
      - ./code:/var/www/drupal
      - ./sites/default:/var/www/drupal/web/sites/default   # override settings stuff
      - ./drush:/var/www/drupal/drush/sites                 # drush aliases from Pantheon
      # expose xdebug config below
      - ./conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    restart: always

  mysql:
    image: mariadb:latest
    restart: always
    hostname: mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 'une'
    volumes:
      - ./db_data:/var/lib/mysql
