<?php

/**
 * @file
 * Https://pantheon.io/docs/redirects/.
 */

//
// You can easily put a list of many 301 url redirects in this format
// Trailing slashes matters here so /old-url1 is different from /old-url1/.
$redirect_targets = [
  '/recycle' => 'http://www.une.edu/sustainability/recycle',
  '/brand' => 'http://www.une.edu/communications/brand',
  '/chp' => 'http://www.une.edu/wchp',
  '/cas/biological' => 'http://www.une.edu/cas/biology',
  '/cas/biological/graduate' => 'http://www.une.edu/cas/biology/graduate',
  '/cas/biological/php' => 'http://www.une.edu/cas/biology/php-advising',
  '/financialaid' => 'http://www.une.edu/sfs',
  '/com/ahec' => 'http://www.une.edu/ahec',
  '/com/publichealth' => 'http://online.une.edu/public-health',
  '/publichealth' => 'http://online.une.edu/public-health',
  '/com/online' => 'http://online.une.edu/science-prerequisites',
  '/lecturesmerrilllecture.cfm' => 'http://www.une.edu/lectures/merrilllecture',
  '/boxoffice' => 'http://www.une.edu/studentlife/portland/involvement-and-activities/une-box-office',
  '/li' => 'http://www.une.edu/?utm_source=schoolguide&utm_medium=printads&utm_content=longisland&utm_campaign=regionalcollegefairads',
  '/nj' => 'http://www.une.edu/?utm_source=schoolguide&utm_medium=printads&utm_content=newjersey&utm_campaign=regionalcollegefairads',
  '/boston' => 'http://www.une.edu/?utm_source=schoolguide&utm_medium=printads&utm_content=boston&utm_campaign=regionalcollegefairads',
  '/usair' => 'http://www.une.edu/?utm_source=usairwaysmag&utm_medium=printad&utm_campaign=usairways',
  '/comresearchday' => 'http://www.une.edu/com/research/research-week',
  '/cas/envstudies/squirrel' => 'https://sites.une.edu/perlutlab/project-squirrel/',
  '/wchp/ipe.cfm' => 'http://www.une.edu/wchp/ipec/',
  '/cec' => 'http://www.une.edu/admissions/undergrad/?utm_source=cec&utm_medium=print&utm_campaign=CEC_ad',
  '/swim' => 'http://www.une.edu/studentlife/biddeford/involvement-activities/wellness/children’s-swim-program',
  '/addverb' => 'http://www.addverbproductions.org',
  '/helpdeskchat' => 'http://its.une.edu/it-help-desk/livechat',
  '/spain' => 'http://www.une.edu/global/ed/seville-spain/?utm_source=direct&utm_medium=print&utm_campaign=spainad',
  '/global/ed/seville' => 'http://www.une.edu/global/ed/seville-spain',
  '/global/ed/spain' => 'http://www.une.edu/global/ed/seville-spain',
  '/jobs' => 'http://www.une.edu/hr/jobs',
  '/uhc/student' => 'http://www.une.edu/studentlife/shc',
  '/ulead' => 'http://www.une.edu/studentlife/biddeford/involvement-activities/leadership-opportunities',
  '/one' => 'http://www.une.edu/giving/annualfund/one/?utm_source=af_mailing&utm_medium=direct&utm_campaign=Annual_Fund_One',
  '/cghlive' => 'http://www.une.edu/cgh/video/live',
  '/cgh/video/live.cfm' => 'http://www.une.edu/cgh/video/live',
  '/manualmedicine' => 'http://www.une.edu/com/cme/omm-series?utm_source=mm_print&utm_medium=direct&utm_campaign=Manual_Medicine',
  '/uhc' => 'http://www.une.edu/com/healthservices',
  '/healthservices' => 'http://www.une.edu/com/healthservices',
  '/frolic' => 'http://www.une.edu/research/msc/marc/get-involved/frolic-4-flippers-5k',
  '/global/ed/morocco' => 'http://www.une.edu/global/ed/tangier-morocco',
  '/tangier' => 'http://www.une.edu/global/ed/tangier-morocco',
  '/whatshappening' => 'https://sites.google.com/a/une.edu/get-involved/?pli=1',
  '/marcgiving' => 'https://securelb.imodules.com/s/1080/index.aspx?sid=1080&gid=1&pgid=418&cid=1215?',
  '/givenow' => 'https://securelb.imodules.com/s/1080/index.aspx?sid=1080&gid=1&pgid=525&cid=1491',
  '/askfinaid' => 'https://i.une.edu/fb/Financial_Aid_Contact_Form.html',
  '/graduation' => 'http://www.une.edu/studentlife/graduation/',
  '/disbursemyloan' => 'https://i.une.edu/fb/une_alternative_loan_request.html',
  '/drifter' => 'https://i.une.edu/fb/Drifter_Study.html',
  '/askstudentaccounts' => 'https://i.une.edu/fb/Ask_Student_Accounts.html',
  '/nurseleader' => 'https://forms.office.com/Pages/ResponsePage.aspx?id=IcWYFJq0h02TDFCO83sfxtZoMqg9B0pIifKlfnnWyjpUQ1ZVRDU3MVdLWDNUNFFUV1EwRzY1T0FXOS4u',
  '/bushlecture' => 'http://www.une.edu/lectures/bush',
  '/bushrsvp' => 'https://securelb.imodules.com/s/1080/index.aspx?sid=1080&gid=1&pgid=700&cid=1871',
  '/wchp/socialwork/online.cfm' => 'http://socialwork.une.edu/?Access_Code=UNE-MSW-SEO2&utm_source=seo2&utm_medium=referral',
  '/uneday' => 'http://www.une.edu/admissions/undergrad/une-day',
  '/housing' => 'http://www.une.edu/studentlife/biddeford/residential/res-ed-office',
  '/dining' => 'https://unedining.catertrax.com/',
  '/campus/dining' => 'https://unedining.catertrax.com/',
  '/studenthealth' => 'http://www.une.edu/studentlife/shc/',
  '/getaround' => 'http://www.une.edu/studentlife/security/getting-around',
  '/career' => 'http://www.une.edu/studentlife/biddeford/career',
  '/studentlife/career' => 'http://www.une.edu/studentlife/biddeford/career',
  '/ebill' => 'https://netpay.higherone.com/NetPay/EBPP/UNE/UNE-Main/Tuition+and+Fees/582/EBPP.aspx',
  '/paymentplan' => 'http://www.une.edu/tuitionpaymentplan',
  '/undergradstartup' => 'http://www.une.edu/sfs/undergraduate/bills-payment-and-refunds',
  '/gradstartup' => 'http://www.une.edu/sfs/graduate/bills-payment-and-refunds',
  '/absnstartup' => 'http://www.une.edu/sfs/undergraduate/bills-payment-and-refunds',
  '/loan' => 'https://studentaid.ed.gov/types/loans/plus',
  '/plusloan' => 'https://www.studentloans.gov',
  '/workstudy' => 'http://www.une.edu/sfs/undergraduate/financing-your-education/federal-work-study-program',
  '/academiccalendar' => 'http://www.une.edu/registrar/calendars',
  '/healthhistory' => 'http://www.une.edu/studentlife/shc',
  '/onlinefinaidapp' => 'https://i.une.edu/fb/unefinancialaidapplication_online.html',
  '/ceipe/ipsat/casecompetition.cfm' => 'http://www.une.edu/wchp/ipec/students/ipsat/une-interprofessional-case-competition',
  '/cas/education/msonline.cfm' => 'http://online.une.edu/education/degrees/',
  '/cas/education/cte-online.cfm' => 'http://online.une.edu/education/degrees/',
  '/cas/education/certificatesonline.cfm' => 'http://online.une.edu/education/degrees/#cags',
  '/cas/education/doctoral/index.cfm' => 'http://online.une.edu/education/doctor-of-education/',
  '/newstudentinstructions' => 'http://www.une.edu/sfs/undergraduate/applying-aid/accounts-setup',
  '/ugcostofattendance' => 'http://www.une.edu/sfs/undergraduate/costs',
  '/satisfactoryacademicprogress' => 'http://www.une.edu/sfs/undergraduate/additional-information/satisfactory-academic-progress',
  '/onlinefinaidapp' => 'https://i.une.edu/fb/unefinancialaidapplication_online.html',
  '/ebilling' => 'https://netpay.higherone.com/NetPay/EBPP/UNE/UNE-Main/Tuition+and+Fees/582/EBPP.aspx',
  '/billing' => 'http://www.une.edu/sfs/undergraduate/bills-payment-and-refunds',
  '/paymybill' => 'http://www.une.edu/sfs/undergraduate/bills-payment-and-refunds',
  '/hr/ads' => 'http://www.une.edu/hr/jobs',
  '/livingexpenses' => 'https://i.une.edu/fb/Living_Expenses_Request.html',
  '/movingforward' => 'http://www.une.edu/giving',
  '/feedback' => 'https://i.une.edu/fb/new_website_feedback.html',
  '/marine' => 'http://www.une.edu/cas/marine',
  '/cas/core' => 'http://www.une.edu/cas/programs/core-curriculum',
  '/admissions/graduate/upload/SSW-Field-Placement-Statement-of-Understanding.pdf' => 'http://www.une.edu/pdfs/school-social-work-field-placement-statement-understanding',
  '/admissions/graduate/upload/referenceform.pdf' => 'http://www.une.edu/pdfs/graduate-admissions-applicant-reference-form',
  '/admissions/graduate/upload/OWLReferenceForm.pdf' => 'http://www.une.edu/pdfs/online-worldwide-learning-applicant-reference-form',
  '/admissions/graduate/upload/ClassroomPlan.pdf' => 'http://www.une.edu/pdfs/classroom-access-plan',
  '/admissions/graduate/upload/MSWOReferenceForm.pdf' => 'http://www.une.edu/pdfs/online-msw-applicant-reference-form',
  '/admissions/graduate/upload/MSWTransferCoursework.pdf' => 'http://www.une.edu/pdfs/msw-transfer-course-work-application',
  '/com/cme/geriatrics11' => 'http://www.une.edu/com/cme/events/geriatrics-conference',
  '/geriatricsconference' => 'http://www.une.edu/com/cme/events/geriatrics-conference',
  '/alzheimerstraining' => 'http://www.une.edu/com/cme/events/preparing-future-alzheimers-disease-related-dementias-training-program',
  '/com/cme/alzheimer.cfm' => 'http://www.une.edu/com/cme/events/preparing-future-alzheimers-disease-related-dementias-training-program',
  '/library/dbtitle.cfm' => 'http://www.une.edu/library/e-resources/databases-title',
  '/library/eresources/ftjournals' => 'http://www.une.edu/library/e-resources/ftjournals',
  '/gecsurvey' => 'https://www.surveymonkey.com/s/UNEMGEC_NeedsAssess2014',
  '/wchp/ipec/interprofessional-collaborative-practice-summit' => 'http://www.une.edu/wchp/ipec/events/ipcp-summit',
  '/wchp/esp/atep' => 'http://www.une.edu/wchp/esp/at',
  '/dlratesandfees' => 'https://studentaid.ed.gov/types/loans/interest-rates',
  '/NursingME' => 'http://www.une.edu/wchp/nursing/programs/accelerated-bachelor-science-nursing?utm_source=anamainejournal&utm_medium=print&utm_campaign=ABSNmaine',
  '/NursingMA' => 'http://www.une.edu/wchp/nursing/programs/accelerated-bachelor-science-nursing?utm_source=massreport&utm_medium=print&utm_campaign=ABSNma',
  '/NurseAnesthesia' => 'http://www.une.edu/wchp/sna?utm_source=anamainejournal&utm_medium=print&utm_campaign=MSNA',
  '/mpbn' => 'http://www.une.edu/?utm_source=MPBN&utm_medium=banner&utm_campaign=MPBN_ad',
  '/timeoffplease' => 'https://i.une.edu/fb/sfs_vacation_time_request.html',
  '/ugSAP' => 'http://www.une.edu/sfs/undergraduate/additional-information/satisfactory-academic-progress',
  '/onlineSAP' => 'http://www.une.edu/sfs/online/additional-information/satisfactory-academic-progress',
  '/gradSAP' => 'http://www.une.edu/sfs/graduate/additional-information/satisfactory-academic-progress',
  '/acceptaward' => 'http://www.une.edu/sfs/undergraduate/applying-aid/accepting-your-award-instructions',
  '/mymoneymatters' => 'http://www.une.edu/sfs/money-matters',
  '/future' => 'http://www.une.edu/admissions?utm_source=usatoday&utm_medium=banner&utm_campaign=future',
  '/library/mguide' => 'http://www.une.edu/library/sguide',
  '/bobolink' => 'http://sites.une.edu/perlutlab',
  '/com/ocs' => 'http://www.une.edu/com/rsas',
  '/myunebill' => 'http://www.une.edu/sfs/undergraduate/bills-payment-and-refunds#payment',
  '/ecoprint' => 'http://its.une.edu/ecoprint',
  '/sites/default/files/personnel_directory_report_20180910.pdf' => 'https://www.une.edu/sites/default/files/personnel_directory_report_20180917.pdf',
  '/autodiscover/autodiscover.xml' => '/',

    // Library redirects.
  '/art-galleries/2017/01/26/zero-los-desplazados-de-colombia-photography-in-black-and-white/' => 'https://library.une.edu/news/2016/une-biddeford-campus-art-gallery-presents-“zero-los-desplazados-de-colombia-photography-black-and﻿/library',
  '/artgallery' => 'https://library.une.edu/art-galleries',
  '/artgallery-4' => 'https://library.une.edu/art-galleries/2014/10/09/coyote-connections/',
  '/artgallery-5' => 'https://library.une.edu/art-galleries/2015/02/03/color-fields-printed-paintings/',
  '/artgallery/biddeford-campus' => 'https://library.une.edu/art-galleries/home/biddeford-campus/',
  '/artgallery/biddeford-campus/exhibitions' => 'https://library.une.edu/art-galleries/home/biddeford-campus/exhibits/',
  '/artgallery/biddeford-campus/exhibitions/past-exhibitions' => 'https://library.une.edu/art-galleries/home/biddeford-campus/exhibits/',
  '/artgallery/biddeford-campus/exhibitions/upcoming-exhibitions' => 'https://library.une.edu/art-galleries/home/biddeford-campus/exhibits/',
  '/artgallery/collection' => 'https://library.une.edu/art-galleries/home/permanent-collection/',
  '/artgallery/exhibitions/13th-annual-sculpture-garden-invitational' => 'https://library.une.edu/art-galleries/2014/06/26/13th-annual-sculpture-garden-invitational/',
  '/artgallery/exhibitions/collage' => 'https://library.une.edu/art-galleries/2014/06/26/making-a-new-whole-the-art-of-collage/',
  '/artgallery/exhibitions/painting-john-calvin-stevens' => 'https://library.une.edu/art-galleries/2015/04/21/the-paintings-of-john-calvin-stevens/',
  '/artgallery/exhibitions/past-exhibitions/2014-art-department-faculty-exhibition' => 'https://library.une.edu/art-galleries/2014/02/05/2014-art-department-faculty-exhibition/',
  '/artgallery/exhibitions/past-exhibitions/a-gateless-garden' => 'https://library.une.edu/art-galleries/2015/01/20/a-gateless-garden/',
  '/artgallery/exhibitions/past-exhibitions/annual-sculpture-garden-invitational-2012' => 'https://library.une.edu/art-galleries/2012/06/08/annual-sculpture-garden-invitational-2012/',
  '/artgallery/exhibitions/past-exhibitions/faces-war-photographic-essay-exhibition-jerry-robinov' => 'https://library.une.edu/art-galleries/2011/11/11/faces-of-war-a-photographic-essay-exhibition-by-jerry-robinov/',
  '/artgallery/exhibitions/past-exhibitions/joe-guertin-graphic-designer-remembered' => 'https://library.une.edu/art-galleries/2013/11/06/joe-guertin-a-graphic-designer-remembered/',
  '/artgallery/exhibitions/past-exhibitions/maine-women-pioneers-iii-dirigo' => 'https://library.une.edu/art-galleries/2013/06/22/maine-women-pioneers-iii-dirigo/',
  '/artgallery/exhibitions/past-exhibitions/maine-women-pioneers-iii-homage' => 'https://library.une.edu/art-galleries/2013/01/02/maine-women-pioneers-iii-homage/',
  '/artgallery/exhibitions/past-exhibitions/maine-women-pioneers-iii-vanguard' => 'https://library.une.edu/art-galleries/2012/10/12/maine-women-pioneers-iii-vanguard/',
  '/artgallery/exhibitions/past-exhibitions/maine-women-pioneers-iii-worldview' => 'https://library.une.edu/art-galleries/2012/03/12/maine-women-pioneers-iii-worldview/',
  '/artgallery/exhibitions/past-exhibitions/mountain-rises-art-katahdin' => 'https://library.une.edu/art-galleries/2013/07/31/a-mountain-rises-the-art-of-katahdin/',
  '/artgallery/exhibitions/past-exhibitions/rebecca-goodale-lullaby-maine' => 'https://library.une.edu/art-galleries/2012/03/15/rebecca-goodale-lullaby-for-maine/',
  '/artgallery/exhibitions/past-exhibitions/upon-reflection-judy-ellis-glickman' => 'https://library.une.edu/art-galleries/2012/06/26/upon-reflection-judy-ellis-glickman/',
  '/artgallery/news' => 'https://library.une.edu/art-galleries/home/news/',
  '/artgallery/news?page=1' => 'https://library.une.edu/art-galleries/home/news/',
  '/artgallery/news?page=10' => 'https://library.une.edu/art-galleries/home/news/',
  '/artgallery/news?page=2' => 'https://library.une.edu/art-galleries/home/news/',
  '/artgallery/news?page=3' => 'https://library.une.edu/art-galleries/home/news/',
  '/artgallery/news?page=4' => 'https://library.une.edu/art-galleries/home/news/',
  '/artgallery/news?page=5' => 'https://library.une.edu/art-galleries/home/news/',
  '/artgallery/news?page=6' => 'https://library.une.edu/art-galleries/home/news/',
  '/artgallery/news?page=7' => 'https://library.une.edu/art-galleries/home/news/',
  '/artgallery/news?page=8' => 'https://library.une.edu/art-galleries/home/news/',
  '/artgallery/news?page=9' => 'https://library.une.edu/art-galleries/home/news/',
  '/artgallery/portland-campus' => 'https://library.une.edu/art-galleries/home/portland-campus/',
  '/artgallery/portland-campus/events' => 'https://library.une.edu/art-galleries/home/news/',
  '/artgallery/portland-campus/exhibitions' => 'https://library.une.edu/art-galleries/home/portland-campus/exhibits/',
  '/artgallery/portland-campus/exhibitions/past-exhibitions' => 'https://library.une.edu/art-galleries/home/portland-campus/exhibits/',
  '/artgallery/portland-campus/exhibitions/upcoming-exhibitions' => 'https://library.une.edu/art-galleries/home/portland-campus/exhibits/',
  '/artgallery/support' => 'https://library.une.edu/art-galleries/home/contact/support-une-art-galleries/',
  '/blc/cushing-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-baird-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-beverly-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-burney-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-bush-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-danielson-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-deibel-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-dodd-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-dolan-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-friend-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-houston-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-jenkins-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-joubert-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-kioske-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-legro-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-long-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-lord-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-lowderback-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-meserve-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-newman-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-nichols-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-shorey-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-slade-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-ward-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-white-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/blc/cushing-collection/guide-wiggin-collection' => 'https://library.une.edu/special-collections/home/collections/cushing-letters/',
  '/library-1' => 'https://library.une.edu/library-resources/find/',
  '/library-6' => 'https://library.une.edu/services-spaces/services-for/alumni/',
  '/library/about' => 'https://library.une.edu/about-contact/',
  '/library/about/contact-us' => 'https://library.une.edu/about-contact/contact-us/',
  '/library/about/contact-us/library-liaisons' => 'https://library.une.edu/services-spaces/classroom-teaching-support/department-liasons/',
  '/library/about/hours' => 'https://library.une.edu/about-contact/hours/',
  '/library/about/policies' => 'https://library.une.edu/about-contact/policies-guidelines/',
  '/library/about/policies/infolit' => 'https://library.une.edu/about-contact/about-une-library-services/information-literacy/',
  '/library/about/policies/library-use-policies' => 'https://library.une.edu/about-contact/policies-guidelines/using-library-spaces/',
  '/library/about/policies/mission-statement' => 'https://library.une.edu/about-contact/about-une-library-services/mission-what-we-do/',
  '/library/about/policies/quarterly-reports' => 'https://library.une.edu/about-contact/about-une-library-services/library-news-events/',
  '/library/about/staff' => 'https://library.une.edu/about-contact/contact-us/staff-directory/',
  '/library/alumni' => 'https://library.une.edu/services-spaces/services-for/alumni/',
  '/library/alumni/alumni-digital-library' => 'https://library.une.edu/services-spaces/services-for/alumni/',
  '/library/alumni/alumni-digital-library/behavioral-and-social-sciences' => 'https://library.une.edu/services-spaces/services-for/alumni/',
  '/library/alumni/alumni-digital-library/education' => 'https://library.une.edu/services-spaces/services-for/alumni/',
  '/library/alumni/alumni-digital-library/environmental-studies' => 'https://library.une.edu/services-spaces/services-for/alumni/',
  '/library/alumni/alumni-digital-library/humanities' => 'https://library.une.edu/services-spaces/services-for/alumni/',
  '/library/alumni/alumni-digital-library/medicine-pharmacy-and-health-sciences' => 'https://library.une.edu/services-spaces/services-for/alumni/',
  '/library/alumni/alumni-digital-library/state-databases' => 'https://library.une.edu/services-spaces/services-for/alumni/state-library-database-list/',
  '/library/databases/mobileapps' => 'https://library.une.edu/research-help/guides-tutorials/using-clinical-mobile-apps/',
  '/library/e-resources/course-guides/wst-337' => 'https://library.une.edu/university-history/university-history/westbrook-college-history/features/researching-19th-and-early-20th-century-womens-higher-education/',
  '/library/e-resources/ebooks' => 'https://library.une.edu/library-resources/find/books-videos/',
  '/library/e-resources/ftjournals' => 'https://library.une.edu/library-resources/find/journals/',
  '/library/e-resources/jourlink' => 'https://library.une.edu/services-spaces/classroom-teaching-support/linking-to-library-resources/',
  '/library/facres' => 'https://library.une.edu/services-spaces/services-for/',
  '/library/facres/affiliate-services' => 'https://library.une.edu/services-spaces/services-for/preceptors-clinical-affiliates/',
  '/library/facres/employee-services' => 'https://library.une.edu/services-spaces/services-for/employees/',
  '/library/facres/faculty-services' => 'https://library.une.edu/services-spaces/services-for/faculty/',
  '/library/facres/library-instruction-to-support-teaching' => 'https://library.une.edu/services-spaces/classroom-teaching-support/library-instruction/',
  '/library/facres/reserve-guidelines' => 'https://library.une.edu/services-spaces/classroom-teaching-support/placing-materials-on-course-reserve/',
  '/library/gethelp' => 'https://library.une.edu/research-help/',
  '/library/gethelp/faq/gpacu' => 'https://library.une.edu/services-spaces/services-for/visitors/gpacu/',
  '/library/gethelp/findjour' => 'https://library.une.edu/research-help/guides-tutorials/find-article/',
  '/library/gethelp/writing' => 'https://library.une.edu/research-help/finding-and-evaluating-sources/',
  '/library/gethelp/writing/scholar' => 'https://library.une.edu/research-help/finding-and-evaluating-sources/scholarly-sources/',
  '/library/gethelp/writing/web-site-evaluation' => 'https://library.une.edu/research-help/finding-and-evaluating-sources/website-blogs-other-internet-sources/',
  '/library/library-1/databases' => 'https://library.une.edu/library-resources/find/databases/',
  '/library/library-1/databases?ltr=U' => 'https://library.une.edu/library-resources/find/databases/',
  '/library/library-1/databases?page=2' => 'https://library.une.edu/library-resources/find/databases/',
  '/library/library-1/databases?page=4' => 'https://library.une.edu/library-resources/find/databases/',
  '/library/online-students' => 'https://library.une.edu/services-spaces/services-for/online-students/',
  '/library/passwords/preview-test-electronic-resources' => 'https://library.une.edu/library-resources/find/databases/',
  '/library/robot' => 'https://library.une.edu/telepresence-robots/',
  '/library/services' => 'https://library.une.edu/services-spaces/borrow/',
  '/library/services/interlibrary-loan-illiad' => 'https://library.une.edu/services-spaces/borrow/interlibrary-loan/',
  '/library/services/mainecat-faqs' => 'https://library.une.edu/services-spaces/borrow/interlibrary-loan/',
  '/library/sguide' => 'https://library.une.edu/research-help/guides-tutorials/research-by-subject/',
  '/library/sguide/animal-behavior' => 'https://library.une.edu/library-materials/find/research-by-subject/animal-behavior/',
  '/library/sguide/anthropology-archaeology' => 'https://library.une.edu/library-materials/find/research-by-subject/anthropology-archaeology/',
  '/library/sguide/applied-exercise-science' => 'https://library.une.edu/library-materials/find/research-by-subject/applied-exercise-science/',
  '/library/sguide/aquaculture-aquarium-sciences' => 'https://library.une.edu/library-materials/find/research-by-subject/aquaculture-aquarium-sciences/',
  '/library/sguide/athletic-training' => 'https://library.une.edu/library-materials/find/research-by-subject/athletic-training/',
  '/library/sguide/biology' => 'https://library.une.edu/library-materials/find/research-by-subject/biology/',
  '/library/sguide/business-administration' => 'https://library.une.edu/library-materials/find/research-by-subject/business-administration/',
  '/library/sguide/chemistry-biochemistry' => 'https://library.une.edu/library-materials/find/research-by-subject/chemistry-biochemistry/',
  '/library/sguide/communications' => 'https://library.une.edu/library-materials/find/research-by-subject/communications/',
  '/library/sguide/creative-and-fine-arts' => 'https://library.une.edu/library-materials/find/research-by-subject/creative-and-fine-arts/',
  '/library/sguide/dental-hygiene' => 'https://library.une.edu/library-materials/find/research-by-subject/dental-hygiene/',
  '/library/sguide/dental-medicine' => 'https://library.une.edu/library-materials/find/research-by-subject/dental-medicine/',
  '/library/sguide/education' => 'https://library.une.edu/library-materials/find/research-by-subject/education/',
  '/library/sguide/english' => 'https://library.une.edu/library-materials/find/research-by-subject/english/',
  '/library/sguide/environmental-sciences-studies' => 'https://library.une.edu/library-materials/find/research-by-subject/environmental-sciences-studies/',
  '/library/sguide/health-informatics' => 'https://library.une.edu/library-materials/find/research-by-subject/health-informatics/',
  '/library/sguide/history' => 'https://library.une.edu/library-materials/find/research-by-subject/history/',
  '/library/sguide/liberal-studies' => 'https://library.une.edu/library-materials/find/research-by-subject/liberal-studies/',
  '/library/sguide/makerspace' => 'https://library.une.edu/library-materials/find/research-by-subject/makerspace/',
  '/library/sguide/marine-sciences' => 'https://library.une.edu/library-materials/find/research-by-subject/marine-sciences/',
  '/library/sguide/mathematical-sciences' => 'https://library.une.edu/library-materials/find/research-by-subject/mathematical-sciences/',
  '/library/sguide/medical-biology' => 'https://library.une.edu/library-materials/find/research-by-subject/medical-biology/',
  '/library/sguide/medicine' => 'https://library.une.edu/library-materials/find/research-by-subject/medicine/',
  '/library/sguide/medicine?fbclid=IwAR1j90-oXjDYUozTQxXfqP8zQfrLyCNCxVdET67ki_y4mXS8PAK3yz8l4fI' => 'https://library.une.edu/library-materials/find/research-by-subject/medicine/',
  '/library/sguide/medicine?fbclid=IwAR39jK7HgzlNONyZ5EKXwQO406knWZTLbPmSjnDRcZmTOg_t_MY-qnxvfmU' => 'https://library.une.edu/library-materials/find/research-by-subject/medicine/',
  '/library/sguide/neuroscience' => 'https://library.une.edu/library-materials/find/research-by-subject/neuroscience/',
  '/library/sguide/nurse-anesthesia' => 'https://library.une.edu/library-materials/find/research-by-subject/nurse-anesthesia/',
  '/library/sguide/nursing' => 'https://library.une.edu/library-materials/find/research-by-subject/nursing/',
  '/library/sguide/nutrition' => 'https://library.une.edu/library-materials/find/research-by-subject/nutrition/',
  '/library/sguide/occupational-therapy' => 'https://library.une.edu/library-materials/find/research-by-subject/occupational-therapy/',
  '/library/sguide/ocean-food-systems' => 'https://library.une.edu/new ',
  '/library/sguide/pharmacy' => 'https://library.une.edu/library-materials/find/research-by-subject/pharmacy/',
  '/library/sguide/philosophy' => 'https://library.une.edu/library-materials/find/research-by-subject/philosophy/',
  '/library/sguide/physical-therapy' => 'https://library.une.edu/library-materials/find/research-by-subject/physical-therapy/',
  '/library/sguide/physician-assistant' => 'https://library.une.edu/library-materials/find/research-by-subject/physician-assistant/',
  '/library/sguide/psychology' => 'https://library.une.edu/library-materials/find/research-by-subject/psychology/',
  '/library/sguide/public-health' => 'https://library.une.edu/library-materials/find/research-by-subject/public-health/',
  '/library/sguide/social-work' => 'https://library.une.edu/library-materials/find/research-by-subject/social-work/',
  '/library/sguide/sociology' => 'https://library.une.edu/library-materials/find/research-by-subject/sociology/',
  '/library/sguide/sport-management' => 'https://library.une.edu/library-materials/find/research-by-subject/sport-management/',
  '/library/sguide/womens-gender-studies' => 'https://library.une.edu/library-materials/find/research-by-subject/womens-gender-studies/',
  '/library/special' => 'https://library.une.edu/library-resources/explore/',
  '/library/special/bush-legacy-collection' => 'https://library.une.edu/special-collections/',
  '/library/special/new-england-osteopathic-heritage-center' => 'https://library.une.edu/neohc',
  '/library/studyrooms' => 'https://library.une.edu/services-spaces/library-spaces/study-rooms/',
  '/mwwc' => 'https://library.une.edu/mwwc',
  '/mwwc-3' => 'https://library.une.edu/mwwc/collections/collections-a-z/mwwc-collection-of-audio-and-video-recording-1970-2011-undated/',
  '/mwwc-4' => 'https://library.une.edu/mwwc/collections/collections-a-z/h-h-price-papers-1983-2009/',
  '/mwwc-5' => 'https://library.une.edu/mwwc/home/exhibits/online/perdita-huston-global-passion-local-action/',
  '/mwwc-6' => 'https://library.une.edu/mwwc/home/exhibits/online/perdita-huston-global-passion-local-action/',
  '/mwwc/collection' => 'https://library.une.edu/mwwc',
  '/mwwc/collection/directions' => 'https://library.une.edu/mwwc/home/contact-visit/locations-directions/',
  '/mwwc/collection/donations-collection' => 'https://library.une.edu/mwwc/home/contact-visit/donations/',
  '/mwwc/conferences-programs-events/creative-writing-workshops' => 'https://library.une.edu/mwwc/home/workshops-events/creative-writing-workshops/',
  '/mwwc/conferences-programs-events/creative-writing-workshops/gathering-writers-workshop' => 'https://library.une.edu/mwwc/home/workshops-events/creative-writing-workshops/',
  '/mwwc/conferences-programs-events/donna-m.-loring-lecture-series' => 'https://library.une.edu/mwwc/home/workshops-events/donna-m-loring-lecture-series/',
  '/mwwc/contact-us' => 'https://library.une.edu/mwwc/home/contact-visit/',
  '/mwwc/programming-events' => 'https://library.une.edu/mwwc/home/workshops-events/',
  '/mwwc/programming-events/academic-conferences' => 'https://library.une.edu/mwwc/home/workshops-events/academic-conferences/',
  '/mwwc/programming-events/author-events' => 'https://library.une.edu/mwwc/home/workshops-events/',
  '/mwwc/programming-events/past-events' => 'https://library.une.edu/mwwc/home/workshops-events/',
  '/mwwc/research' => 'https://library.une.edu/mwwc/home/research-support/',
  '/mwwc/research/collections' => 'https://library.une.edu/mwwc/home/collections/',
  '/mwwc/research/collections/a-carman-clark-papers-1934-2005' => 'https://library.une.edu/mwwc/collections/collections-a-z/a-carman-clark-papers-1917-2005/',
  '/mwwc/research/collections/lael-morgan-papers-1936-2012' => 'https://library.une.edu/mwwc/collections/collections-a-z/lael-morgan-papers-1936-2017/',
  '/mwwc/research/creative-fellow-program' => 'https://library.une.edu/mwwc/home/research-support/creative-fellow-grants/',
  '/mwwc/research/featured-writers/abbie-bartlett-shapleigh-correspondence-1860-1892' => 'https://library.une.edu/mwwc/collections/collections-a-z/abbie-bartlett-shapleigh-correspondence-1860-1902/',
  '/mwwc/research/featured-writers/ann-beattie-papers-1976-1996' => 'https://library.une.edu/mwwc/collections/collections-a-z/ann-beattie-papers-1976-1996-undated/',
  '/mwwc/research/featured-writers/ann-sophia-winterbotham-stephens-collection-1835-1892' => 'https://library.une.edu/mwwc/collections/collections-a-z/ann-s-stephens-collection-1835-1980/',
  '/mwwc/research/featured-writers/anna-barrows-papers-1861-1948' => 'https://library.une.edu/mwwc/collections/collections-a-z/anna-barrows-papers-1839-1948-undated/',
  '/mwwc/research/featured-writers/anne-hazlewood-brady-papers-1958-2001' => 'https://library.une.edu/mwwc/collections/collections-a-z/anne-hazlewood-brady-papers-1958-2001/',
  '/mwwc/research/featured-writers/audrey-white-beyer-papers-1935-1985' => 'https://library.une.edu/mwwc/collections/collections-a-z/audrey-white-beyer-papers-1935-1985/',
  '/mwwc/research/featured-writers/barbara-banker-kamar-collection-1885-2012' => 'https://library.une.edu/mwwc/collections/collections-a-z/barbara-banker-kamar-collection-1885-2012-undated/',
  '/mwwc/research/featured-writers/barbara-cooney-collection-1986-1996' => 'https://library.une.edu/mwwc/collections/collections-a-z/maine-women-writers-reference-collection-1856-2013/',
  '/mwwc/research/featured-writers/berenice-abbott-collection-1950-1991' => 'https://library.une.edu/mwwc/collections/collections-a-z/berenice-abbott-collection-1950-1991/',
  '/mwwc/research/featured-writers/bhima-macdonald-sturtevant-papers-1856-1974' => 'https://library.une.edu/mwwc/collections/collections-a-z/bhima-macdonald-sturtevant-papers-1814-2000/',
  '/mwwc/research/featured-writers/blaisdell-family-letters-1879-1916' => 'https://library.une.edu/mwwc/collections/collections-a-z/blaisdell-family-letters-1879-1916/',
  '/mwwc/research/featured-writers/blanche-willis-howard-collection-1847-1898' => 'https://library.une.edu/mwwc/collections/collections-a-z/blanche-willis-howard-collection-1847-1906/',
  '/mwwc/research/featured-writers/carolyn-chute-collection-1984-2002' => 'https://library.une.edu/mwwc/collections/collections-a-z/carolyn-chute-collection-1984-2009/',
  '/mwwc/research/featured-writers/cathie-pelletier-papers-1959-2002' => 'https://library.une.edu/mwwc/collections/collections-a-z/cathie-pelletier-papers-1963-2003/',
  '/mwwc/research/featured-writers/chenoweth-hall-slides-1952-1986' => 'https://library.une.edu/mwwc/collections/collections-a-z/chenoweth-hall-collection-1952-1986/',
  '/mwwc/research/featured-writers/christine-teale-howes-collection-1979-2011' => 'https://library.une.edu/mwwc/collections/collections-a-z/christine-teale-howes-collection-1979-1995/',
  '/mwwc/research/featured-writers/clifford-flanders-family-collection-circa-1852-1989' => 'https://library.une.edu/mwwc/collections/collections-a-z/clifford-flanders-family-papers-circa-1852-1989/',
  '/mwwc/research/featured-writers/clubs-organizations-associations-collection' => 'https://library.une.edu/mwwc/collections/collections-a-z/clubs-organizations-and-associations-collection-1803-1987/',
  '/mwwc/research/featured-writers/constance-hunting-collection-1979-1996' => 'https://library.une.edu/mwwc/collections/collections-a-z/constance-hunting-collection-1979-1996/',
  '/mwwc/research/featured-writers/dahlov-ipcar-papers-1966-2000' => 'https://library.une.edu/mwwc/collections/collections-a-z/dahlov-ipcar-collection-1966-2000/',
  '/mwwc/research/featured-writers/donna-m.-loring-papers-1956-2008' => 'https://library.une.edu/mwwc/collections/collections-a-z/donna-m-loring-papers-1956-2016-undated/',
  '/mwwc/research/featured-writers/dorothea-lynde-dix-1848-1974' => 'https://library.une.edu/mwwc/collections/collections-a-z/dorothea-lynde-dix-collection-1848-1974/',
  '/mwwc/research/featured-writers/dorothy-clarke-wilson-collection-1926-1989' => 'https://library.une.edu/mwwc/collections/collections-a-z/dorothy-clarke-wilson-papers-1926-1989/',
  '/mwwc/research/featured-writers/edna-st.-vincent-millay-collection-1900-1992' => 'https://library.une.edu/mwwc/collections/collections-a-z/edna-st-vincent-millay-collection-1900-1992/',
  '/mwwc/research/featured-writers/elisabeth-may-ogilvie-collection-1985-2003' => 'https://library.une.edu/mwwc/collections/collections-a-z/elisabeth-may-ogilvie-papers-1933-2006/',
  '/mwwc/research/featured-writers/elizabeth-akers-allen-collection-1866-1911' => 'https://library.une.edu/mwwc/collections/collections-a-z/elizabeth-akers-allen-papers-1866-1911/',
  '/mwwc/research/featured-writers/elizabeth-foster-collection-1942-1994' => 'https://library.une.edu/mwwc/collections/collections-a-z/elizabeth-foster-collection-1942-1994/',
  '/mwwc/research/featured-writers/elizabeth-jane-coatsworth-papers-1900-1985' => 'https://library.une.edu/mwwc/collections/collections-a-z/elizabeth-jane-coatsworth-papers-1900-1985/',
  '/mwwc/research/featured-writers/elizabeth-oakes-smith-collection-1842-2006' => 'https://library.une.edu/mwwc/collections/collections-a-z/elizabeth-oakes-smith-collection-1842-2007/',
  '/mwwc/research/featured-writers/ethel-godfrey-loud-collection' => 'https://library.une.edu/mwwc/collections/collections-a-z/ethel-godfrey-loud-collection-1880-1959/',
  '/mwwc/research/featured-writers/fannie-hardy-eckstorm-collection-1917-1996' => 'https://library.une.edu/mwwc/collections/collections-a-z/fannie-hardy-eckstorm-collection-1917-1996/',
  '/mwwc/research/featured-writers/frances-wilson-peabody-papers-1980-1997' => 'https://library.une.edu/mwwc/collections/collections-a-z/frances-peabody-papers-1920-1997/',
  '/mwwc/research/featured-writers/gladys-hasty-carroll-collection-1919-1999' => 'https://library.une.edu/mwwc/collections/collections-a-z/gladys-hasty-carroll-collection-1919-1999/',
  '/mwwc/research/featured-writers/harriet-beecher-stowe-collection-1880-1899' => 'https://library.une.edu/mwwc/collections/collections-a-z/harriet-beecher-stowe-collection-1880-1999/',
  '/mwwc/research/featured-writers/harriet-prescott-spofford-papers-1860-1912' => 'https://library.une.edu/mwwc/collections/collections-a-z/harriet-elizabeth-prescott-spofford-collection-1891-2004/',
  '/mwwc/research/featured-writers/ina-ladd-brown-collection-1957-1984' => 'https://library.une.edu/mwwc/collections/collections-a-z/ina-ladd-brown-collection-1957-1984/',
  '/mwwc/research/featured-writers/josephine-diebitsch-peary-collection-1861-2003' => 'https://library.une.edu/mwwc/collections/collections-a-z/josephine-diebitsch-peary-papers-1861-2003/',
  '/mwwc/research/featured-writers/joyce-butler-collection-1970-1986' => 'https://library.une.edu/mwwc/collections/collections-a-z/joyce-butler-collection-1969-2014/',
  '/mwwc/research/featured-writers/judith-magyar-isaacson-papers-1976-1990' => 'https://library.une.edu/mwwc/collections/collections-a-z/judith-magyar-isaacson-papers-1976-1990/',
  '/mwwc/research/featured-writers/kate-douglas-wiggin-collection-1883-1997' => 'https://library.une.edu/mwwc/collections/collections-a-z/kate-douglas-wiggin-collection-1883-1938/',
  '/mwwc/research/featured-writers/katharine-obrien-papers-1905-1986' => 'https://library.une.edu/mwwc/collections/collections-a-z/katharine-e-obrien-papers-1905-1986/',
  '/mwwc/research/featured-writers/katy-perry-papers-1966-2011' => 'https://library.une.edu/mwwc/collections/collections-a-z/katy-perry-papers-1966-2012/',
  '/mwwc/research/featured-writers/laura-elizabeth-howe-richards-collection-1884-1969' => 'https://library.une.edu/mwwc/collections/collections-a-z/laura-elizabeth-howe-richards-papers-1884-1969/',
  '/mwwc/research/featured-writers/linda-tatelbaum-collection-1947' => 'https://library.une.edu/mwwc/collections/collections-a-z/linda-tatelbaum-papers-1972-2003/',
  '/mwwc/research/featured-writers/louise-bogan-collection-1934-1985' => 'https://library.une.edu/mwwc/collections/collections-a-z/louise-bogan-collection-1934-1985/',
  '/mwwc/research/featured-writers/maine-association-women-fine-and-performing-arts-records-1977' => 'https://library.une.edu/mwwc/collections/collections-a-z/maine-association-of-women-in-the-fine-and-performing-arts-records-1977-1983-undated/',
  '/mwwc/research/featured-writers/manuscript-volumes-collection-1838-1952' => 'https://library.une.edu/mwwc/collections/collections-a-z/manuscript-volumes-collection-1838-1952-undated/',
  '/mwwc/research/featured-writers/margaret-jane-mussey-sweat-collection-1834-1907' => 'https://library.une.edu/mwwc/collections/collections-a-z/margaret-j-m-sweat-papers-1835-2005-undated/',
  '/mwwc/research/featured-writers/margaret-wade-campbell-deland-collection-1925-1991' => 'https://library.une.edu/mwwc/collections/collections-a-z/margaret-wade-campbell-deland-collection-1925-1991/',
  '/mwwc/research/featured-writers/marie-ahnighito-peary-papers-1893-1978' => 'https://library.une.edu/mwwc/collections/collections-a-z/marie-ahnighito-peary-papers-1862-1995/',
  '/mwwc/research/featured-writers/marie-donahue-papers-1929-2007' => 'https://library.une.edu/mwwc/collections/collections-a-z/marie-donahue-papers-1929-2007/',
  '/mwwc/research/featured-writers/martha-.-hall-collection-1998-2003' => 'https://library.une.edu/mwwc/collections/collections-a-z/martha-a-hall-collection-1998-2003/',
  '/mwwc/research/featured-writers/mary-calvert-collection-1904-2000' => 'https://library.une.edu/mwwc/collections/collections-a-z/mary-r-calvert-collection-1975-1996/',
  '/mwwc/research/featured-writers/mary-ellen-chase-papers-1902-1973' => 'https://library.une.edu/mwwc/collections/collections-a-z/mary-ellen-chase-papers-1902-1973/',
  '/mwwc/research/featured-writers/may-sarton-collection-1860-1994' => 'https://library.une.edu/mwwc/collections/collections-a-z/may-sarton-papers-1860-1994/',
  '/mwwc/research/featured-writers/miriam-colwell-papers-1945-1998' => 'https://library.une.edu/mwwc/collections/collections-a-z/miriam-colwell-collection-1945-1998/',
  '/mwwc/research/featured-writers/mwwc-reference-collection-1856-2005' => 'https://library.une.edu/mwwc/collections/collections-a-z/maine-women-writers-reference-collection-1856-2013/',
  '/mwwc/research/featured-writers/nora-archibald-smith-papers-1878-2009' => 'https://library.une.edu/mwwc/collections/collections-a-z/nora-archibald-smith-papers-1878-2009/',
  '/mwwc/research/featured-writers/perdita-huston-papers-1961-2001' => 'https://library.une.edu/mwwc/collections/collections-a-z/perdita-huston-papers-1936-2007/',
  '/mwwc/research/featured-writers/phyllis-schuyler-thaxter-collection-1890-1969' => 'https://library.une.edu/mwwc/collections/collections-a-z/phyllis-schuyler-thaxter-collection-1890-1998/',
  '/mwwc/research/featured-writers/rachel-l.-carson-collection-1946-1964' => 'https://library.une.edu/mwwc/collections/collections-a-z/rachel-carson-collection-1946-1964/',
  '/mwwc/research/featured-writers/rachel-lyman-field-collection-1925-1971' => 'https://library.une.edu/mwwc/collections/collections-a-z/rachel-field-collection-1925-1971/',
  '/mwwc/research/featured-writers/ramona-barth-collection-1880-1990' => 'https://library.une.edu/mwwc/collections/collections-a-z/ramona-barth-papers-1880-2002-undated/',
  '/mwwc/research/featured-writers/ruth-moore-collection-1917-1995' => 'https://library.une.edu/mwwc/collections/collections-a-z/ruth-moore-collection-1917-1995/',
  '/mwwc/research/featured-writers/sally-sayward-barrell-keating-wood-collection-1845-1998' => 'https://library.une.edu/mwwc/collections/collections-a-z/sally-sayward-barrell-keating-wood-collection-1800-1998/',
  '/mwwc/research/featured-writers/sandra-featherman-papers-1967-2008' => 'https://library.une.edu/mwwc/collections/collections-a-z/sandra-featherman-papers-1967-2008/',
  '/mwwc/research/featured-writers/sara-payson-willis-parton-fanny-fern-1853-1872' => 'https://library.une.edu/mwwc/collections/collections-a-z/fanny-fern-collection-1853-1872/',
  '/mwwc/research/featured-writers/sarah-orne-jewett-collection-1801-1997' => 'https://library.une.edu/mwwc/collections/collections-a-z/sarah-orne-jewett-collection-1801-1997/',
  '/mwwc/research/featured-writers/sarah-wood-frost-correspondence-1815-1822' => 'https://library.une.edu/mwwc/collections/collections-a-z/sarah-wood-frost-correspondence-1815-1822/',
  '/mwwc/research/featured-writers/smith-family-papers-1878-1935' => 'https://library.une.edu/mwwc/collections/collections-a-z/smith-family-papers-1878-1935/',
  '/mwwc/research/featured-writers/sue-mcconkey-collection-1912-2001' => 'https://library.une.edu/mwwc/collections/collections-a-z/sue-mcconkey-papers-1912-2001/',
  '/mwwc/research/featured-writers/theodora-j.-kalikow-collection-1974-2012' => 'https://library.une.edu/mwwc/collections/collections-a-z/theodora-j-kalikow-collection-1968-2016/',
  '/mwwc/research/featured-writers/virginia-chase-collection-1910-1987' => 'https://library.une.edu/mwwc/collections/collections-a-z/virginia-chase-papers-1910-1987/',
  '/mwwc/research/research-support-grants-recipients' => 'https://library.une.edu/mwwc/home/research-support/research-support-grants/',
  '/mwwc/research/search-tools-library-mwwc-archives' => 'https://library.une.edu/mwwc/home/collections/',
  '/mwwc/research/search-tools-library-mwwc-archives/non-book-materials-inventory-authors-a-f' => 'https://library.une.edu/mwwc/home/collections/browse-collections/',
  '/mwwc/research/search-tools-library-mwwc-archives/non-book-materials-inventory-authors-g-l' => 'https://library.une.edu/mwwc/home/collections/browse-collections/',
  '/mwwc/research/search-tools-library-mwwc-archives/non-book-materials-inventory-authors-m-s' => 'https://library.une.edu/mwwc/home/collections/browse-collections/',
  '/mwwc/research/search-tools-library-mwwc-archives/non-book-materials-inventory-authors-t-z' => 'https://library.une.edu/mwwc/home/collections/browse-collections/',
  '/mwwc/research/undergraduate-research' => 'https://library.une.edu/mwwc/home/research-support/resources-for-faculty/',
  '/mwwc/research/visitor-policies' => 'https://library.une.edu/mwwc/home/contact-visit/information-for-visitors/',
  '/neohc/collections' => 'https://library.une.edu/neohc/home/collections/browse-all-collections/',
  '/neohc/collections/guide-cranston-general-hospital-collection' => 'https://library.une.edu/neohc/home/collections/browse-all-collections/',
  '/mwwc/research/featured-writers/florence-burrill-jacobs-papers-1904-1976' => 'https://library.une.edu/mwwc/collections/collections-a-z/florence-burrill-jacobs-papers-1904-1976',
  '/neohc/contact-us' => 'https://library.une.edu/neohc/home/contact-visit/',
  '/neohc/research-support-grant-program' => 'https://library.une.edu/neohc/home/research-support-grants/',
  '/news/2015/art-gallery-presents-‘a-gateless-garden-quotes-maine-women-writers’' => 'https://library.une.edu/art-galleries/2016/08/24/a-gateless-garden-quotes-by-maine-women-writers/',
  '/schc' => 'https://library.une.edu/university-history/university-history/st-francis-college-history/',
  '/schc/collections' => 'https://library.une.edu/university-history/university-history/st-francis-college-history/browse-collection/',
  '/schc/contact-us' => 'https://library.une.edu/university-history/university-history/st-francis-college-history/contact/',
  '/sites/default/files/timeline2.pdf' => 'https://library.une.edu/university-history/university-history/westbrook-college-history/exhibits/',
  '/wchc' => 'https://library.une.edu/university-history/university-history/westbrook-college-history/',
  '/wchc/alumni-authors' => 'https://library.une.edu/university-history/university-history/westbrook-college-history/features/westbrook-college-alumni-authors/',
  '/wchc/collections/guide-alumni-affairs-records-1845-2012' => 'https://library.une.edu/university-history/collections/collections-a-z/alumni-affairs-records-1845-2012/',
  '/wchc/collections/guide-board-trustees-records-1842-1996' => 'https://library.une.edu/university-history/collections/collections-a-z/board-of-trustees-records-1842-1996/',
  '/wchc/collections/guide-commencement-programs-ephemera-and-speeches-1868-1999' => 'https://library.une.edu/university-history/collections/collections-a-z/commencement-programs-ephemera-and-speeches-1868-1999/',
  '/wchc/collections/guide-communications-office-records-1970-1996' => 'https://library.une.edu/university-history/collections/collections-a-z/communications-office-records-1970-1996/',
  '/wchc/collections/guide-continuing-education-records-1950-1992' => 'https://library.une.edu/university-history/collections/collections-a-z/continuing-education-records-1950-1992/',
  '/wchc/collections/guide-dean-college-records-1928-1995' => 'https://library.une.edu/university-history/collections/collections-a-z/dean-of-the-college-records-1928-1995/',
  '/wchc/collections/guide-director-library-records-1967-2003' => 'https://library.une.edu/university-history/collections/collections-a-z/director-of-the-library-records-1967-2003/',
  '/wchc/collections/guide-dorothy-healy-collection-1900-1987' => 'https://library.une.edu/university-history/collections/collections-a-z/dorothy-m-healy-collection/',
  '/wchc/collections/guide-faculty-senate-records-1878-1997' => 'https://library.une.edu/university-history/collections/collections-a-z/faculty-collection-1878-1996/',
  '/wchc/collections/guide-financial-aid-office-records-1980-1997' => 'https://library.une.edu/university-history/collections/collections-a-z/financial-aid-office-records-1980-1997/',
  '/wchc/collections/guide-office-dean-college-records-i-1959-1995' => 'https://library.une.edu/university-history/collections/collections-a-z/office-of-the-dean-of-the-college-records-i-1959-1995/',
  '/wchc/collections/guide-office-dean-college-records-ii-1928-2001' => 'https://library.une.edu/university-history/collections/collections-a-z/office-of-the-dean-of-the-college-records-ii-1928-2001/',
  '/wchc/collections/guide-president-edward-york-blewett-records-1938-1986' => 'https://library.une.edu/university-history/collections/collections-a-z/president-edward-york-blewett-records-1938-1986/',
  '/wchc/collections/guide-president-james-dickinson-records-1958-1977' => 'https://library.une.edu/university-history/collections/collections-a-z/president-james-dickinson-records-1958-1977/',
  '/wchc/collections/guide-president-milton-d-proctor-records-1927-1958' => 'https://library.une.edu/university-history/collections/collections-a-z/president-milton-d-proctor-records-1927-1958/',
  '/wchc/collections/guide-president-thomas-b-courtice-records-1977-1986' => 'https://library.une.edu/university-history/collections/collections-a-z/president-thomas-b-courtice-records-1977-1986/',
  '/wchc/collections/guide-president-william-d-andrews-collection-1987-1996' => 'https://library.une.edu/university-history/collections/collections-a-z/president-william-d-andrews-collection-1987-1996/',
  '/wchc/collections/guide-presidents-westbrook-college-collection-1834-1996' => 'https://library.une.edu/university-history/collections/collections-a-z/presidents-of-westbrook-college-collection-1834-1996/',
  '/wchc/collections/guide-registrars-records-1850-1984' => 'https://library.une.edu/university-history/collections/collections-a-z/registrars-records-1850-1984/',
  '/wchc/collections/guide-roberta-gray-collection-1932-1994' => 'https://library.une.edu/university-history/collections/collections-a-z/roberta-gray-collection-1932-1994/',
  '/wchc/collections/guide-student-development-records-1853-1997' => 'https://library.une.edu/university-history/collections/collections-a-z/student-development-records-1853-1997/',
  '/wchc/collections/guide-treasurer-records-1890-1974' => 'https://library.une.edu/university-history/collections/collections-a-z/treasurer-records-1890-1974/',
  '/wchc/collections/guide-vice-president-external-affairs-papers-1988-1997' => 'https://library.une.edu/university-history/collections/collections-a-z/vice-president-of-external-affairs-papers-1988-1997/',
  '/wchc/collections/guide-westbrook-college-catalogs-1844-1996' => 'https://library.une.edu/university-history/collections/collections-a-z/westbrook-college-catalogs-1844-1996/',
  '/wchc/collections/guide-yearbooks-1935-1996' => 'https://library.une.edu/university-history/collections/collections-a-z/yearbooks-1935-1996/',
  '/wchc/contact' => 'https://library.une.edu/university-history/university-history/westbrook-college-history/contact/',
  '/wchc/wchc-historical-postcards-gallery' => 'https://library.une.edu/university-history/university-history/westbrook-college-history/features/westbrook-college-history-collection-historical-postcards/',
  '/neohc/collections' => 'https://library.une.edu/neohc/home/collections/',
  '/library/gethelp/writing/annotated-bibliography' => 'https://library.une.edu/research-help/guides-tutorials/course-guides/writing-an-annotated-bibliography/',
  '/library/gethelp/writing/webeval' => 'https://library.une.edu/research-help/finding-and-evaluating-sources/website-blogs-other-internet-sources/',
  '/sites/default/files/evaluateanejournalunelibraryservices2018.pdf' => 'https://library.une.edu/wp-content/uploads/2019/07/EvaluationOnlineJournal.pdf',
  '/library/e-resources' => 'https://library.une.edu/library-resources',
  '/library/gethelp/campus-access' => 'https://library.une.edu',
];

if ((isset($redirect_targets[$_SERVER['REQUEST_URI']])) && (php_sapi_name() != "cli")) {

  echo $redirect_targets[$_SERVER['REQUEST_URI']];
  header('HTTP/1.0 301 Moved Permanently');
  header('Location: ' . $redirect_targets[$_SERVER['REQUEST_URI']]);

  if (extension_loaded('newrelic')) {
    newrelic_name_transaction("redirect");
  }
  exit();
}

// Redirect all /calendar to /events.
$uri = $_SERVER['request_uri'];
$url_to_match = '/calendar';
$subdirectory_toredirect = '/events';

if ((php_sapi_name() != "cli") && strpos($uri, $url_to_match) === 0) {
  $redirect_uri = str_replace($url_to_match, "", $uri);

  header('http/1.0 301 moved permanently');
  header('location: https://' . $_SERVER['http_host'] . $subdirectory_toredirect . $redirect_uri);
  if (extension_loaded('newrelic')) {
    newrelic_name_transaction("redirect");
  }
  exit();
}

// redirect all /calendar to /events
$uri = $_server['request_uri'];
$url_to_match = '/calendar';
$subdirectory_toredirect = '/events';

if( strpos( $uri, $url_to_match ) === 0) {

  $redirect_uri = str_replace( $url_to_match , "", $uri );
  if ( ( php_sapi_name() != "cli" ) ) {
    header( 'http/1.0 301 moved permanently');
    header( 'location: https://' . $_server[ 'http_host' ] . $subdirectory_toredirect . $redirect_uri );

    if (extension_loaded('newrelic')) {
      newrelic_name_transaction("redirect");
    }

    exit();
  }

}
